#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build the app as a Nuitka onefile executable with license config embedded."""

import argparse
import shutil
import subprocess
import sys
from pathlib import Path
from typing import List, Optional


PROJECT_ROOT = Path(__file__).resolve().parent
LICENSE_CONFIG = PROJECT_ROOT / "core" / "license_public_key.py"
DIST_DIR = PROJECT_ROOT / "dist_nuitka"
OUTPUT_NAME = "岭南师范学院教务管理助手.exe"


def run_command(command: List[str], cwd: Optional[Path] = None) -> None:
    print("[执行]", " ".join(command))
    subprocess.run(command, cwd=str(cwd or PROJECT_ROOT), check=True)


def ensure_python_package(import_name: str, package_name: str) -> None:
    try:
        __import__(import_name)
    except ImportError:
        run_command([sys.executable, "-m", "pip", "install", package_name])


def install_runtime_dependencies() -> None:
    requirements = PROJECT_ROOT / "requirements.txt"
    if requirements.exists():
        run_command([sys.executable, "-m", "pip", "install", "-r", str(requirements)])
    ensure_python_package("nuitka", "nuitka")
    ensure_python_package("zstandard", "zstandard")
    ensure_python_package("ordered_set", "ordered-set")


def write_license_config(license_url: str, public_key_path: str, cache_grace_days: int) -> None:
    public_key = Path(public_key_path).read_text(encoding="utf-8").strip()
    content = f'''"""Build-time license configuration.

Generated by build_nuitka.py. This file contains only public data.
"""

PUBLIC_KEY_PEM = {public_key!r}
LICENSE_URL = {license_url!r}
CACHE_GRACE_DAYS = {cache_grace_days!r}
'''
    LICENSE_CONFIG.write_text(content, encoding="utf-8")
    print(f"[授权] 已写入公钥和授权地址: {LICENSE_CONFIG}")


def clean_build_dirs() -> None:
    paths = [
        DIST_DIR,
        PROJECT_ROOT / "main.build",
        PROJECT_ROOT / "main.dist",
        PROJECT_ROOT / "main.onefile-build",
    ]
    for path in paths:
        if path.exists():
            if path.is_dir():
                shutil.rmtree(path)
            else:
                path.unlink()


def build_nuitka_command(extra_args: Optional[List[str]] = None) -> List[str]:
    icon_path = PROJECT_ROOT / "ui" / "assets" / "icon.ico"
    command = [
        sys.executable,
        "-m",
        "nuitka",
        "--standalone",
        "--onefile",
        "--enable-plugin=pyqt6",
        "--windows-console-mode=disable",
        "--deployment",
        "--lto=yes",
        "--python-flag=no_asserts",
        "--python-flag=no_docstrings",
        "--mingw64",
        "--assume-yes-for-downloads",
        "--output-dir=dist_nuitka",
        f"--output-filename={OUTPUT_NAME}",
        "--include-data-file=config.ini.example=config.ini.example",
        "--remove-output",
    ]
    if icon_path.exists():
        command.append(f"--windows-icon-from-ico={icon_path}")
    if extra_args:
        command.extend(extra_args)
    command.append("main.py")
    return command


def build_onefile(extra_args: Optional[List[str]] = None) -> None:
    command = build_nuitka_command(extra_args=extra_args)
    run_command(command)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="使用 Nuitka 打包授权版 exe")
    parser.add_argument("--license-url", required=True, help="Gitee raw licenses.json 地址")
    parser.add_argument("--public-key", required=True, help="RSA 公钥 pem 文件路径")
    parser.add_argument("--cache-grace-days", type=int, default=3, help="离线缓存宽限天数")
    parser.add_argument("--skip-install", action="store_true", help="跳过依赖安装检查")
    parser.add_argument(
        "--nuitka-arg",
        action="append",
        default=[],
        help="追加传给 Nuitka 的参数，可重复使用",
    )
    return parser


def main(argv: Optional[List[str]] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if not args.skip_install:
        install_runtime_dependencies()

    write_license_config(args.license_url, args.public_key, args.cache_grace_days)
    clean_build_dirs()
    build_onefile(extra_args=args.nuitka_arg)

    exe_path = DIST_DIR / OUTPUT_NAME
    if exe_path.exists():
        print(f"[完成] {exe_path}")
        print(f"[大小] {exe_path.stat().st_size / 1024 / 1024:.1f} MB")
        return 0

    print("[失败] 未找到生成的 exe")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
