"""Build-time license configuration.

Generated by build_nuitka.py. This file contains only public data.
"""

PUBLIC_KEY_PEM = '-----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEAh2IAL8xoz33TZm/AviqMTnTDqdCQFb5Gh7LROG68DpLo3Oa+3nCp\nhtQxeBcpyveMI6qJPQWoSaBOjk/jgPjnp8GYpGJjznSQ1l+dtkHrvgedxPKYtINz\niMyUX6QmYYiRAgc6pTE0FyMCL+ze1Uc6sIJOBvLmJ1yS2f4HihLjg5ZQrwi7tHG1\n+H2mv2QuoRn5qoY7iWHxHz0eBnZ0TDPKk69k8cDxlMlVgKNkbcpU4Mrn6kYnT3iz\nSsReZjIOyJfXFWqOKZe05vcf9rABvX4KNG7/ExdsiMSjnR7qTKJaQq11xN/qPYli\nya4OPf4SdUTOS5DRTTeOpt8q5SRnxC3QQQIDAQAB\n-----END RSA PUBLIC KEY-----'
LICENSE_URL = 'https://gitee.com/ConfusePack/HWID_2/raw/master/licenses.json'
CACHE_GRACE_DAYS = 3
